"""Sensors backed by typed components and pure derived measurements."""

from dataclasses import dataclass
from typing import Any, override

from homeassistant.components.sensor import (
    RestoreSensor,
    SensorDeviceClass,
    SensorEntity,
    SensorEntityDescription,
    SensorStateClass,
)
from homeassistant.const import EntityCategory
from homeassistant.core import HomeAssistant, callback
from homeassistant.helpers.entity_platform import AddConfigEntryEntitiesCallback

from .coordinator import SungrowConfigEntry
from .entity import SungrowDescription, SungrowEntity, is_supported

PARALLEL_UPDATES = 0


@dataclass(frozen=True, kw_only=True)
class SungrowSensorDescription(SensorEntityDescription, SungrowDescription):
    """One sensor and its source dependencies."""


SENSORS: tuple[SungrowSensorDescription, ...] = (
    SungrowSensorDescription(
        key="version_1",
        translation_key="version_1",
        component="legacy_firmware",
        field="version_1",
        dependencies=("legacy_firmware",),
        source_fields=(("legacy_firmware", "version_1"),),
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SungrowSensorDescription(
        key="version_2",
        translation_key="version_2",
        component="legacy_firmware",
        field="version_2",
        dependencies=("legacy_firmware",),
        source_fields=(("legacy_firmware", "version_2"),),
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SungrowSensorDescription(
        key="version_3",
        translation_key="version_3",
        component="legacy_firmware",
        field="version_3",
        dependencies=("legacy_firmware",),
        source_fields=(("legacy_firmware", "version_3"),),
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SungrowSensorDescription(
        key="version_4_sungrow_battery",
        translation_key="version_4_sungrow_battery",
        component="legacy_firmware",
        field="version_4_sungrow_battery",
        dependencies=("legacy_firmware",),
        source_fields=(("legacy_firmware", "version_4_sungrow_battery"),),
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SungrowSensorDescription(
        key="protocol_version",
        translation_key="protocol_version",
        component="software",
        field="protocol_version",
        dependencies=("software",),
        source_fields=(("software", "protocol_version"),),
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SungrowSensorDescription(
        key="arm_software",
        translation_key="arm_software",
        component="software",
        field="arm_software",
        dependencies=("software",),
        source_fields=(("software", "arm_software"),),
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SungrowSensorDescription(
        key="dsp_software",
        translation_key="dsp_software",
        component="software",
        field="dsp_software",
        dependencies=("software",),
        source_fields=(("software", "dsp_software"),),
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SungrowSensorDescription(
        key="inverter_serial",
        translation_key="inverter_serial",
        component="identity",
        field="inverter_serial",
        dependencies=("identity",),
        source_fields=(("identity", "inverter_serial"),),
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SungrowSensorDescription(
        key="device_type_code",
        translation_key="device_type_code",
        component="identity",
        field="device_type_code",
        dependencies=("identity",),
        source_fields=(("identity", "device_type_code"),),
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SungrowSensorDescription(
        key="inverter_rated_output",
        translation_key="inverter_rated_output",
        component="identity",
        field="inverter_rated_output",
        dependencies=("identity",),
        source_fields=(("identity", "inverter_rated_output"),),
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement="W",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SungrowSensorDescription(
        key="daily_pv_generation_battery_discharge",
        translation_key="daily_pv_generation_battery_discharge",
        component="combined_energy",
        field="daily_pv_generation_battery_discharge",
        dependencies=("combined_energy",),
        source_fields=(("combined_energy", "daily_pv_generation_battery_discharge"),),
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kWh",
        state_class=SensorStateClass.TOTAL_INCREASING,
        suggested_display_precision=1,
        entity_registry_enabled_default=False,
    ),
    SungrowSensorDescription(
        key="total_pv_generation_battery_discharge",
        translation_key="total_pv_generation_battery_discharge",
        component="combined_energy",
        field="total_pv_generation_battery_discharge",
        dependencies=("combined_energy",),
        source_fields=(("combined_energy", "total_pv_generation_battery_discharge"),),
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kWh",
        state_class=SensorStateClass.TOTAL,
        suggested_display_precision=1,
        entity_registry_enabled_default=False,
    ),
    SungrowSensorDescription(
        key="inverter_temperature",
        translation_key="inverter_temperature",
        component="inverter_temperature",
        field="inverter_temperature",
        dependencies=("inverter_temperature",),
        source_fields=(("inverter_temperature", "inverter_temperature"),),
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement="°C",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="mppt1_voltage",
        translation_key="mppt1_voltage",
        component="pv",
        field="mppt1_voltage",
        dependencies=("pv",),
        source_fields=(("pv", "mppt1_voltage"),),
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement="V",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="mppt1_current",
        translation_key="mppt1_current",
        component="pv",
        field="mppt1_current",
        dependencies=("pv",),
        source_fields=(("pv", "mppt1_current"),),
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement="A",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="mppt2_voltage",
        translation_key="mppt2_voltage",
        component="pv",
        field="mppt2_voltage",
        dependencies=("pv",),
        source_fields=(("pv", "mppt2_voltage"),),
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement="V",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="mppt2_current",
        translation_key="mppt2_current",
        component="pv",
        field="mppt2_current",
        dependencies=("pv",),
        source_fields=(("pv", "mppt2_current"),),
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement="A",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="mppt3_voltage",
        translation_key="mppt3_voltage",
        component="pv",
        field="mppt3_voltage",
        dependencies=("pv",),
        source_fields=(("pv", "mppt3_voltage"),),
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement="V",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="mppt3_current",
        translation_key="mppt3_current",
        component="pv",
        field="mppt3_current",
        dependencies=("pv",),
        source_fields=(("pv", "mppt3_current"),),
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement="A",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="total_dc_power",
        translation_key="total_dc_power",
        component="pv",
        field="total_dc_power",
        dependencies=("pv",),
        source_fields=(("pv", "total_dc_power"),),
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement="W",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="phase_a_voltage",
        translation_key="phase_a_voltage",
        component="grid",
        field="phase_a_voltage",
        dependencies=("grid",),
        source_fields=(("grid", "phase_a_voltage"),),
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement="V",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="phase_b_voltage",
        translation_key="phase_b_voltage",
        component="grid",
        field="phase_b_voltage",
        dependencies=("grid",),
        source_fields=(("grid", "phase_b_voltage"),),
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement="V",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="phase_c_voltage",
        translation_key="phase_c_voltage",
        component="grid",
        field="phase_c_voltage",
        dependencies=("grid",),
        source_fields=(("grid", "phase_c_voltage"),),
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement="V",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="reactive_power",
        translation_key="reactive_power",
        component="grid",
        field="reactive_power",
        dependencies=("grid",),
        source_fields=(("grid", "reactive_power"),),
        device_class=SensorDeviceClass.REACTIVE_POWER,
        native_unit_of_measurement="var",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="power_factor",
        translation_key="power_factor",
        component="grid",
        field="power_factor",
        dependencies=("grid",),
        source_fields=(("grid", "power_factor"),),
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=3,
    ),
    SungrowSensorDescription(
        key="mppt4_voltage",
        translation_key="mppt4_voltage",
        component="pv",
        field="mppt4_voltage",
        dependencies=("pv",),
        source_fields=(("pv", "mppt4_voltage"),),
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement="V",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="mppt4_current",
        translation_key="mppt4_current",
        component="pv",
        field="mppt4_current",
        dependencies=("pv",),
        source_fields=(("pv", "mppt4_current"),),
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement="A",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="battery_power",
        translation_key="battery_power",
        component="battery",
        field="battery_power",
        dependencies=("battery",),
        source_fields=(("battery", "battery_power"),),
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement="W",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="grid_frequency",
        translation_key="grid_frequency",
        component="grid",
        field="grid_frequency",
        dependencies=("grid",),
        source_fields=(("grid", "grid_frequency"),),
        device_class=SensorDeviceClass.FREQUENCY,
        native_unit_of_measurement="Hz",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=2,
    ),
    SungrowSensorDescription(
        key="meter_active_power",
        translation_key="meter_active_power",
        component="meter_power",
        field="meter_active_power",
        dependencies=("meter_power",),
        source_fields=(("meter_power", "meter_active_power"),),
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement="W",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="meter_phase_a_active_power",
        translation_key="meter_phase_a_active_power",
        component="meter_power",
        field="meter_phase_a_active_power",
        dependencies=("meter_power",),
        source_fields=(("meter_power", "meter_phase_a_active_power"),),
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement="W",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="meter_phase_b_active_power",
        translation_key="meter_phase_b_active_power",
        component="meter_power",
        field="meter_phase_b_active_power",
        dependencies=("meter_power",),
        source_fields=(("meter_power", "meter_phase_b_active_power"),),
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement="W",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="meter_phase_c_active_power",
        translation_key="meter_phase_c_active_power",
        component="meter_power",
        field="meter_phase_c_active_power",
        dependencies=("meter_power",),
        source_fields=(("meter_power", "meter_phase_c_active_power"),),
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement="W",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="export_power_limit_min",
        translation_key="export_power_limit_min",
        component="export_bounds",
        field="export_power_limit_min",
        dependencies=("export_bounds",),
        source_fields=(("export_bounds", "export_power_limit_min"),),
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement="W",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SungrowSensorDescription(
        key="export_power_limit_max",
        translation_key="export_power_limit_max",
        component="export_bounds",
        field="export_power_limit_max",
        dependencies=("export_bounds",),
        source_fields=(("export_bounds", "export_power_limit_max"),),
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement="W",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SungrowSensorDescription(
        key="bdc_rated_power",
        translation_key="bdc_rated_power",
        component="battery_info",
        field="bdc_rated_power",
        dependencies=("battery_info",),
        source_fields=(("battery_info", "bdc_rated_power"),),
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement="W",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SungrowSensorDescription(
        key="battery_current",
        translation_key="battery_current",
        component="battery",
        field="battery_current",
        dependencies=("battery",),
        source_fields=(("battery", "battery_current"),),
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement="A",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="bms_max_charging_current",
        translation_key="bms_max_charging_current",
        component="battery_info",
        field="bms_max_charging_current",
        dependencies=("battery_info",),
        source_fields=(("battery_info", "bms_max_charging_current"),),
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement="A",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="bms_max_discharging_current",
        translation_key="bms_max_discharging_current",
        component="battery_info",
        field="bms_max_discharging_current",
        dependencies=("battery_info",),
        source_fields=(("battery_info", "bms_max_discharging_current"),),
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement="A",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="battery_capacity_high_precision",
        translation_key="battery_capacity_high_precision",
        component="battery_info",
        field="battery_capacity_high_precision",
        dependencies=("battery_info",),
        source_fields=(("battery_info", "battery_capacity_high_precision"),),
        device_class=SensorDeviceClass.ENERGY_STORAGE,
        native_unit_of_measurement="kWh",
        suggested_display_precision=2,
    ),
    SungrowSensorDescription(
        key="backup_phase_a_power",
        translation_key="backup_phase_a_power",
        component="backup",
        field="backup_phase_a_power",
        dependencies=("backup",),
        source_fields=(("backup", "backup_phase_a_power"),),
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement="W",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="backup_phase_b_power",
        translation_key="backup_phase_b_power",
        component="backup",
        field="backup_phase_b_power",
        dependencies=("backup",),
        source_fields=(("backup", "backup_phase_b_power"),),
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement="W",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="backup_phase_c_power",
        translation_key="backup_phase_c_power",
        component="backup",
        field="backup_phase_c_power",
        dependencies=("backup",),
        source_fields=(("backup", "backup_phase_c_power"),),
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement="W",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="total_backup_power",
        translation_key="total_backup_power",
        component="backup",
        field="total_backup_power",
        dependencies=("backup",),
        source_fields=(("backup", "total_backup_power"),),
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement="W",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="running_state_raw",
        translation_key="running_state_raw",
        component="state",
        field="running_state_raw",
        dependencies=("state",),
        source_fields=(("state", "running_state_raw"),),
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SungrowSensorDescription(
        key="power_flow_status",
        translation_key="power_flow_status",
        component="state",
        field="power_flow_status",
        dependencies=("state",),
        source_fields=(("state", "power_flow_status"),),
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SungrowSensorDescription(
        key="daily_pv_generation",
        translation_key="daily_pv_generation",
        component="energy",
        field="daily_pv_generation",
        dependencies=("energy",),
        source_fields=(("energy", "daily_pv_generation"),),
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kWh",
        state_class=SensorStateClass.TOTAL_INCREASING,
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="total_pv_generation",
        translation_key="total_pv_generation",
        component="energy",
        field="total_pv_generation",
        dependencies=("energy",),
        source_fields=(("energy", "total_pv_generation"),),
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kWh",
        state_class=SensorStateClass.TOTAL,
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="daily_exported_energy_from_pv",
        translation_key="daily_exported_energy_from_pv",
        component="energy",
        field="daily_exported_energy_from_pv",
        dependencies=("energy",),
        source_fields=(("energy", "daily_exported_energy_from_pv"),),
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kWh",
        state_class=SensorStateClass.TOTAL_INCREASING,
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="total_exported_energy_from_pv",
        translation_key="total_exported_energy_from_pv",
        component="energy",
        field="total_exported_energy_from_pv",
        dependencies=("energy",),
        source_fields=(("energy", "total_exported_energy_from_pv"),),
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kWh",
        state_class=SensorStateClass.TOTAL,
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="load_power",
        translation_key="load_power",
        component="state",
        field="load_power",
        dependencies=("state",),
        source_fields=(("state", "load_power"),),
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement="W",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="export_power_raw",
        translation_key="export_power_raw",
        component="grid_flow",
        field="export_power_raw",
        dependencies=("grid_flow",),
        source_fields=(("grid_flow", "export_power_raw"),),
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement="W",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="daily_battery_charge_from_pv",
        translation_key="daily_battery_charge_from_pv",
        component="energy",
        field="daily_battery_charge_from_pv",
        dependencies=("energy",),
        source_fields=(("energy", "daily_battery_charge_from_pv"),),
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kWh",
        state_class=SensorStateClass.TOTAL_INCREASING,
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="total_battery_charge_from_pv",
        translation_key="total_battery_charge_from_pv",
        component="energy",
        field="total_battery_charge_from_pv",
        dependencies=("energy",),
        source_fields=(("energy", "total_battery_charge_from_pv"),),
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kWh",
        state_class=SensorStateClass.TOTAL,
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="daily_direct_energy_consumption",
        translation_key="daily_direct_energy_consumption",
        component="energy",
        field="daily_direct_energy_consumption",
        dependencies=("energy",),
        source_fields=(("energy", "daily_direct_energy_consumption"),),
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kWh",
        state_class=SensorStateClass.TOTAL_INCREASING,
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="total_direct_energy_consumption",
        translation_key="total_direct_energy_consumption",
        component="energy",
        field="total_direct_energy_consumption",
        dependencies=("energy",),
        source_fields=(("energy", "total_direct_energy_consumption"),),
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kWh",
        state_class=SensorStateClass.TOTAL,
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="battery_voltage",
        translation_key="battery_voltage",
        component="battery",
        field="battery_voltage",
        dependencies=("battery",),
        source_fields=(("battery", "battery_voltage"),),
        device_class=SensorDeviceClass.VOLTAGE,
        native_unit_of_measurement="V",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="battery_level",
        translation_key="battery_level",
        component="battery_status",
        field="battery_level",
        dependencies=("battery_status",),
        source_fields=(("battery_status", "battery_level"),),
        device_class=SensorDeviceClass.BATTERY,
        native_unit_of_measurement="%",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="battery_state_of_health",
        translation_key="battery_state_of_health",
        component="battery_health",
        field="battery_state_of_health",
        dependencies=("battery_health",),
        source_fields=(("battery_health", "battery_state_of_health"),),
        native_unit_of_measurement="%",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="battery_temperature",
        translation_key="battery_temperature",
        component="battery_status",
        field="battery_temperature",
        dependencies=("battery_status",),
        source_fields=(("battery_status", "battery_temperature"),),
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement="°C",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="daily_battery_discharge",
        translation_key="daily_battery_discharge",
        component="energy",
        field="daily_battery_discharge",
        dependencies=("energy",),
        source_fields=(("energy", "daily_battery_discharge"),),
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kWh",
        state_class=SensorStateClass.TOTAL_INCREASING,
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="total_battery_discharge",
        translation_key="total_battery_discharge",
        component="energy",
        field="total_battery_discharge",
        dependencies=("energy",),
        source_fields=(("energy", "total_battery_discharge"),),
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kWh",
        state_class=SensorStateClass.TOTAL,
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="phase_a_current",
        translation_key="phase_a_current",
        component="grid_output",
        field="phase_a_current",
        dependencies=("grid_output",),
        source_fields=(("grid_output", "phase_a_current"),),
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement="A",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="phase_b_current",
        translation_key="phase_b_current",
        component="grid_output",
        field="phase_b_current",
        dependencies=("grid_output",),
        source_fields=(("grid_output", "phase_b_current"),),
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement="A",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="phase_c_current",
        translation_key="phase_c_current",
        component="grid_output",
        field="phase_c_current",
        dependencies=("grid_output",),
        source_fields=(("grid_output", "phase_c_current"),),
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement="A",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="total_active_power",
        translation_key="total_active_power",
        component="grid_output",
        field="total_active_power",
        dependencies=("grid_output",),
        source_fields=(("grid_output", "total_active_power"),),
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement="W",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="daily_imported_energy",
        translation_key="daily_imported_energy",
        component="energy",
        field="daily_imported_energy",
        dependencies=("energy",),
        source_fields=(("energy", "daily_imported_energy"),),
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kWh",
        state_class=SensorStateClass.TOTAL_INCREASING,
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="total_imported_energy",
        translation_key="total_imported_energy",
        component="energy",
        field="total_imported_energy",
        dependencies=("energy",),
        source_fields=(("energy", "total_imported_energy"),),
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kWh",
        state_class=SensorStateClass.TOTAL,
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="daily_battery_charge",
        translation_key="daily_battery_charge",
        component="energy",
        field="daily_battery_charge",
        dependencies=("energy",),
        source_fields=(("energy", "daily_battery_charge"),),
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kWh",
        state_class=SensorStateClass.TOTAL_INCREASING,
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="total_battery_charge",
        translation_key="total_battery_charge",
        component="energy",
        field="total_battery_charge",
        dependencies=("energy",),
        source_fields=(("energy", "total_battery_charge"),),
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kWh",
        state_class=SensorStateClass.TOTAL,
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="daily_exported_energy",
        translation_key="daily_exported_energy",
        component="energy",
        field="daily_exported_energy",
        dependencies=("energy",),
        source_fields=(("energy", "daily_exported_energy"),),
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kWh",
        state_class=SensorStateClass.TOTAL_INCREASING,
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="total_exported_energy",
        translation_key="total_exported_energy",
        component="energy",
        field="total_exported_energy",
        dependencies=("energy",),
        source_fields=(("energy", "total_exported_energy"),),
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kWh",
        state_class=SensorStateClass.TOTAL,
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="load_adjustment_mode_selection_raw",
        translation_key="load_adjustment_mode_selection_raw",
        component="load_settings",
        field="load_adjustment_mode_selection_raw",
        dependencies=("load_settings",),
        source_fields=(("load_settings", "load_adjustment_mode_selection_raw"),),
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SungrowSensorDescription(
        key="load_adjustment_mode_enable_raw",
        translation_key="load_adjustment_mode_enable_raw",
        component="load_settings",
        field="load_adjustment_mode_enable_raw",
        dependencies=("load_settings",),
        source_fields=(("load_settings", "load_adjustment_mode_enable_raw"),),
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SungrowSensorDescription(
        key="ems_mode_selection_raw",
        translation_key="ems_mode_selection_raw",
        component="battery_settings",
        field="ems_mode_selection_raw",
        dependencies=("battery_settings",),
        source_fields=(("battery_settings", "ems_mode_selection_raw"),),
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SungrowSensorDescription(
        key="battery_forced_charge_discharge_cmd_raw",
        translation_key="battery_forced_charge_discharge_cmd_raw",
        component="battery_settings",
        field="battery_forced_charge_discharge_cmd_raw",
        dependencies=("battery_settings",),
        source_fields=(
            ("battery_settings", "battery_forced_charge_discharge_cmd_raw"),
        ),
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SungrowSensorDescription(
        key="battery_forced_charge_discharge_power",
        translation_key="battery_forced_charge_discharge_power",
        component="battery_settings",
        field="battery_forced_charge_discharge_power",
        dependencies=("battery_settings",),
        source_fields=(("battery_settings", "battery_forced_charge_discharge_power"),),
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement="W",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SungrowSensorDescription(
        key="battery_max_soc",
        translation_key="battery_max_soc",
        component="battery_settings",
        field="battery_max_soc",
        dependencies=("battery_settings",),
        source_fields=(("battery_settings", "battery_max_soc"),),
        device_class=SensorDeviceClass.BATTERY,
        native_unit_of_measurement="%",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SungrowSensorDescription(
        key="battery_min_soc",
        translation_key="battery_min_soc",
        component="battery_settings",
        field="battery_min_soc",
        dependencies=("battery_settings",),
        source_fields=(("battery_settings", "battery_min_soc"),),
        device_class=SensorDeviceClass.BATTERY,
        native_unit_of_measurement="%",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=1,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SungrowSensorDescription(
        key="export_power_limit",
        translation_key="export_power_limit",
        component="export_settings",
        field="export_power_limit",
        dependencies=("export_settings",),
        source_fields=(("export_settings", "export_power_limit"),),
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement="W",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SungrowSensorDescription(
        key="backup_mode_raw",
        translation_key="backup_mode_raw",
        component="export_settings",
        field="backup_mode_raw",
        dependencies=("export_settings",),
        source_fields=(("export_settings", "backup_mode_raw"),),
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SungrowSensorDescription(
        key="export_power_limit_mode_raw",
        translation_key="export_power_limit_mode_raw",
        component="export_settings",
        field="export_power_limit_mode_raw",
        dependencies=("export_settings",),
        source_fields=(("export_settings", "export_power_limit_mode_raw"),),
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SungrowSensorDescription(
        key="active_power_limitation_raw",
        translation_key="active_power_limitation_raw",
        component="active_limitation",
        field="active_power_limitation_raw",
        dependencies=("active_limitation",),
        source_fields=(("active_limitation", "active_power_limitation_raw"),),
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SungrowSensorDescription(
        key="active_power_limitation_ratio_raw",
        translation_key="active_power_limitation_ratio_raw",
        component="active_limitation",
        field="active_power_limitation_ratio_raw",
        dependencies=("active_limitation",),
        source_fields=(("active_limitation", "active_power_limitation_ratio_raw"),),
        native_unit_of_measurement="%",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SungrowSensorDescription(
        key="battery_reserved_soc_for_backup",
        translation_key="battery_reserved_soc_for_backup",
        component="battery_settings",
        field="battery_reserved_soc_for_backup",
        dependencies=("battery_settings",),
        source_fields=(("battery_settings", "battery_reserved_soc_for_backup"),),
        device_class=SensorDeviceClass.BATTERY,
        native_unit_of_measurement="%",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SungrowSensorDescription(
        key="inverter_firmware_version",
        translation_key="inverter_firmware_version",
        component="inverter_firmware",
        field="inverter_firmware_version",
        dependencies=("inverter_firmware",),
        source_fields=(("inverter_firmware", "inverter_firmware_version"),),
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SungrowSensorDescription(
        key="communication_module_firmware_version",
        translation_key="communication_module_firmware_version",
        component="communication_firmware",
        field="communication_module_firmware_version",
        dependencies=("communication_firmware",),
        source_fields=(
            ("communication_firmware", "communication_module_firmware_version"),
        ),
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SungrowSensorDescription(
        key="battery_firmware_version",
        translation_key="battery_firmware_version",
        component="battery_firmware",
        field="battery_firmware_version",
        dependencies=("battery_firmware",),
        source_fields=(("battery_firmware", "battery_firmware_version"),),
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SungrowSensorDescription(
        key="apl_shutdown_at_zero_raw",
        translation_key="apl_shutdown_at_zero_raw",
        component="apl",
        field="apl_shutdown_at_zero_raw",
        dependencies=("apl",),
        source_fields=(("apl", "apl_shutdown_at_zero_raw"),),
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SungrowSensorDescription(
        key="battery_max_charge_power",
        translation_key="battery_max_charge_power",
        component="battery_limits",
        field="battery_max_charge_power",
        dependencies=("battery_limits",),
        source_fields=(("battery_limits", "battery_max_charge_power"),),
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement="W",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SungrowSensorDescription(
        key="battery_max_discharge_power",
        translation_key="battery_max_discharge_power",
        component="battery_limits",
        field="battery_max_discharge_power",
        dependencies=("battery_limits",),
        source_fields=(("battery_limits", "battery_max_discharge_power"),),
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement="W",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SungrowSensorDescription(
        key="battery_charging_start_power",
        translation_key="battery_charging_start_power",
        component="battery_thresholds",
        field="battery_charging_start_power",
        dependencies=("battery_thresholds",),
        source_fields=(("battery_thresholds", "battery_charging_start_power"),),
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement="W",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SungrowSensorDescription(
        key="battery_discharging_start_power",
        translation_key="battery_discharging_start_power",
        component="battery_thresholds",
        field="battery_discharging_start_power",
        dependencies=("battery_thresholds",),
        source_fields=(("battery_thresholds", "battery_discharging_start_power"),),
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement="W",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    SungrowSensorDescription(
        key="mppt1_power",
        translation_key="mppt1_power",
        component="derived",
        field="mppt1_power",
        dependencies=("pv",),
        source_fields=(("pv", "mppt1_current"), ("pv", "mppt1_voltage")),
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement="W",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SungrowSensorDescription(
        key="mppt2_power",
        translation_key="mppt2_power",
        component="derived",
        field="mppt2_power",
        dependencies=("pv",),
        source_fields=(("pv", "mppt2_current"), ("pv", "mppt2_voltage")),
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement="W",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SungrowSensorDescription(
        key="mppt3_power",
        translation_key="mppt3_power",
        component="derived",
        field="mppt3_power",
        dependencies=("pv",),
        source_fields=(("pv", "mppt3_current"), ("pv", "mppt3_voltage")),
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement="W",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SungrowSensorDescription(
        key="mppt4_power",
        translation_key="mppt4_power",
        component="derived",
        field="mppt4_power",
        dependencies=("pv",),
        source_fields=(("pv", "mppt4_current"), ("pv", "mppt4_voltage")),
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement="W",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SungrowSensorDescription(
        key="phase_a_power",
        translation_key="phase_a_power",
        component="derived",
        field="phase_a_power",
        dependencies=("grid", "grid_output"),
        source_fields=(("grid", "phase_a_voltage"), ("grid_output", "phase_a_current")),
        device_class=SensorDeviceClass.APPARENT_POWER,
        native_unit_of_measurement="VA",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SungrowSensorDescription(
        key="phase_b_power",
        translation_key="phase_b_power",
        component="derived",
        field="phase_b_power",
        dependencies=("grid", "grid_output"),
        source_fields=(("grid", "phase_b_voltage"), ("grid_output", "phase_b_current")),
        device_class=SensorDeviceClass.APPARENT_POWER,
        native_unit_of_measurement="VA",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SungrowSensorDescription(
        key="phase_c_power",
        translation_key="phase_c_power",
        component="derived",
        field="phase_c_power",
        dependencies=("grid", "grid_output"),
        source_fields=(("grid", "phase_c_voltage"), ("grid_output", "phase_c_current")),
        device_class=SensorDeviceClass.APPARENT_POWER,
        native_unit_of_measurement="VA",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SungrowSensorDescription(
        key="inverter_state",
        translation_key="inverter_state",
        component="derived",
        field="inverter_state",
        dependencies=("state",),
        source_fields=(("state", "running_state_raw"),),
    ),
    SungrowSensorDescription(
        key="device_type",
        translation_key="device_type",
        component="derived",
        field="device_type",
        dependencies=("identity",),
        source_fields=(("identity", "device_type_code"),),
    ),
    SungrowSensorDescription(
        key="battery_charging_power_signed",
        translation_key="battery_charging_power_signed",
        component="derived",
        field="battery_charging_power_signed",
        dependencies=("battery",),
        source_fields=(("battery", "battery_power"),),
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement="W",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SungrowSensorDescription(
        key="battery_charging_power",
        translation_key="battery_charging_power",
        component="derived",
        field="battery_charging_power",
        dependencies=("battery",),
        source_fields=(("battery", "battery_power"),),
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement="W",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SungrowSensorDescription(
        key="battery_discharging_power_signed",
        translation_key="battery_discharging_power_signed",
        component="derived",
        field="battery_discharging_power_signed",
        dependencies=("battery",),
        source_fields=(("battery", "battery_power"),),
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement="W",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SungrowSensorDescription(
        key="battery_discharging_power",
        translation_key="battery_discharging_power",
        component="derived",
        field="battery_discharging_power",
        dependencies=("battery",),
        source_fields=(("battery", "battery_power"),),
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement="W",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SungrowSensorDescription(
        key="import_power",
        translation_key="import_power",
        component="derived",
        field="import_power",
        dependencies=("grid_flow",),
        source_fields=(("grid_flow", "export_power_raw"),),
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement="W",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SungrowSensorDescription(
        key="export_power",
        translation_key="export_power",
        component="derived",
        field="export_power",
        dependencies=("grid_flow",),
        source_fields=(("grid_flow", "export_power_raw"),),
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement="W",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SungrowSensorDescription(
        key="battery_level_nominal",
        translation_key="battery_level_nominal",
        component="derived",
        field="battery_level_nominal",
        dependencies=("battery_settings", "battery_status"),
        source_fields=(
            ("battery_settings", "battery_max_soc"),
            ("battery_settings", "battery_min_soc"),
            ("battery_status", "battery_level"),
        ),
        device_class=SensorDeviceClass.BATTERY,
        native_unit_of_measurement="%",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SungrowSensorDescription(
        key="battery_charge_nominal",
        translation_key="battery_charge_nominal",
        component="derived",
        field="battery_charge_nominal",
        dependencies=("battery_info", "battery_settings", "battery_status"),
        source_fields=(
            ("battery_info", "battery_capacity_high_precision"),
            ("battery_settings", "battery_max_soc"),
            ("battery_settings", "battery_min_soc"),
            ("battery_status", "battery_level"),
        ),
        device_class=SensorDeviceClass.ENERGY_STORAGE,
        native_unit_of_measurement="kWh",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SungrowSensorDescription(
        key="battery_charge",
        translation_key="battery_charge",
        component="derived",
        field="battery_charge",
        dependencies=("battery_info", "battery_settings", "battery_status"),
        source_fields=(
            ("battery_info", "battery_capacity_high_precision"),
            ("battery_settings", "battery_max_soc"),
            ("battery_settings", "battery_min_soc"),
            ("battery_status", "battery_level"),
        ),
        device_class=SensorDeviceClass.ENERGY_STORAGE,
        native_unit_of_measurement="kWh",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SungrowSensorDescription(
        key="battery_charge_health_rated",
        translation_key="battery_charge_health_rated",
        component="derived",
        field="battery_charge_health_rated",
        dependencies=(
            "battery_health",
            "battery_info",
            "battery_settings",
            "battery_status",
        ),
        source_fields=(
            ("battery_health", "battery_state_of_health"),
            ("battery_info", "battery_capacity_high_precision"),
            ("battery_settings", "battery_max_soc"),
            ("battery_settings", "battery_min_soc"),
            ("battery_status", "battery_level"),
        ),
        device_class=SensorDeviceClass.ENERGY_STORAGE,
        native_unit_of_measurement="kWh",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SungrowSensorDescription(
        key="daily_consumed_energy",
        translation_key="daily_consumed_energy",
        component="derived",
        field="daily_consumed_energy",
        dependencies=("energy",),
        source_fields=(
            ("energy", "daily_battery_charge"),
            ("energy", "daily_battery_discharge"),
            ("energy", "daily_exported_energy"),
            ("energy", "daily_imported_energy"),
            ("energy", "daily_pv_generation"),
        ),
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kWh",
        state_class=SensorStateClass.TOTAL,
    ),
    SungrowSensorDescription(
        key="total_consumed_energy",
        translation_key="total_consumed_energy",
        component="derived",
        field="total_consumed_energy",
        dependencies=("energy",),
        source_fields=(
            ("energy", "total_battery_charge"),
            ("energy", "total_battery_discharge"),
            ("energy", "total_exported_energy"),
            ("energy", "total_imported_energy"),
            ("energy", "total_pv_generation"),
        ),
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement="kWh",
        state_class=SensorStateClass.TOTAL,
    ),
)


async def async_setup_entry(
    hass: HomeAssistant,
    entry: SungrowConfigEntry,
    async_add_entities: AddConfigEntryEntitiesCallback,
) -> None:
    """Create only sensors supported by the identified model."""
    async_add_entities(
        (
            SungrowTotalSensor
            if description.state_class
            in (SensorStateClass.TOTAL, SensorStateClass.TOTAL_INCREASING)
            else SungrowSensor
        )(entry.runtime_data, description)
        for description in SENSORS
        if is_supported(entry.runtime_data, description)
    )


class SungrowSensor(SungrowEntity, SensorEntity):
    """A live measurement."""

    entity_description: SungrowSensorDescription

    @property
    @override
    def native_value(self) -> Any:
        """Return the decoded or derived measurement without replacing missing data."""
        return self._value()


class SungrowTotalSensor(SungrowEntity, RestoreSensor):
    """Retain and restore energy totals through normal inverter outages."""

    entity_description: SungrowSensorDescription

    @property
    @override
    def available(self) -> bool:
        """Keep cached totals internally, but do not present stale values as live."""
        return super().available and self._attr_native_value is not None

    @override
    async def async_added_to_hass(self) -> None:
        """Restore the last energy value before subscribing."""
        await super().async_added_to_hass()
        if (stored := await self.async_get_last_sensor_data()) is not None:
            self._attr_native_value = stored.native_value
        self._process_data()

    def _process_data(self) -> None:
        """Process data."""
        if super().available and (value := self._value()) is not None:
            self._attr_native_value = value

    @callback
    @override
    def _handle_coordinator_update(self) -> None:
        """Handle coordinator update."""
        self._process_data()
        super()._handle_coordinator_update()
